ALTER TABLE jobs
ADD COLUMN city VARCHAR(255),
ADD COLUMN state VARCHAR(255),
ADD COLUMN employment_type VARCHAR(255) NOT NULL,
ADD COLUMN salary DECimal(10, 2) NULL,
ADD COLUMN vacancies INT,
ADD COLUMN seniority_level VARCHAR(255) NOT NULL;
